// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJRCDM5IXnBFDtd44zanr-3j8U_Aq-24',
    appId: '1:629758088814:web:21a36e481cbf72943eb87f',
    messagingSenderId: '629758088814',
    projectId: 'lovegot-d8943',
    authDomain: 'lovegot-d8943.firebaseapp.com',
    storageBucket: 'lovegot-d8943.firebasestorage.app',
    measurementId: 'G-3CD262S8BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIVjIOjgy6Mrzaqg-L_UHbTPxCKsmA-XA',
    appId: '1:629758088814:android:8208ff707c13b7203eb87f',
    messagingSenderId: '629758088814',
    projectId: 'lovegot-d8943',
    storageBucket: 'lovegot-d8943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGkgKR-7yjDMkdCdw0rT6mKTiSw59J5E',
    appId: '1:629758088814:ios:17d4e8581984e64a3eb87f',
    messagingSenderId: '629758088814',
    projectId: 'lovegot-d8943',
    storageBucket: 'lovegot-d8943.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFGkgKR-7yjDMkdCdw0rT6mKTiSw59J5E',
    appId: '1:629758088814:ios:17d4e8581984e64a3eb87f',
    messagingSenderId: '629758088814',
    projectId: 'lovegot-d8943',
    storageBucket: 'lovegot-d8943.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJRCDM5IXnBFDtd44zanr-3j8U_Aq-24',
    appId: '1:629758088814:web:a61f3a8091a49dde3eb87f',
    messagingSenderId: '629758088814',
    projectId: 'lovegot-d8943',
    authDomain: 'lovegot-d8943.firebaseapp.com',
    storageBucket: 'lovegot-d8943.firebasestorage.app',
    measurementId: 'G-LFG2BZB491',
  );
}
